[package]
name = "llm"
version = "0.1.0"
edition = "2021"

[dependencies]
db = { path = "../db/" }

anyhow = "1.0.94"
aws-config = "1.5.10"
aws-sdk-bedrockruntime = { version = "1.64.0", features = [
    "behavior-version-latest",
] }
lambda_runtime = "0.13.0"
pgvector = { version = "0.4.0", features = ["diesel", "serde"] }
serde_json = "1.0.133"
